CREATE TABLE Airplane(
SNID INTEGER PRIMARY KEY NOT NULL,
capacity INTEGER NOT NULL,
max_speed REAL NOT NULL
)

CREATE TABLE PrivateJet(
owner_name VARCHAR(40),
FOREIGN KEY(SNID) REFERENCES(Airplane) ON DELETE CASCADE
)


CREATE TABLE CommercialPlane(
airline_name VARCHAR(40),
FOREIGN KEY(SNID) REFERENCES(Airplane) ON DELETE CASCADE
)
