CREATE TABLE Airplane(
SNID INTEGER PRIMARY KEY NOT NULL,
capacity INTEGER NOT NULL,
max_speed REAL NOT NULL
)

CREATE TABLE PrivateJet (
    SNID INTEGER PRIMARY KEY,
    owner_name VARCHAR(40),
    FOREIGN KEY (SNID) REFERENCES Airplane (SNID) ON DELETE CASCADE
);

CREATE TABLE CommercialPlane (
    SNID INTEGER PRIMARY KEY,
    airline_name VARCHAR(40),
    FOREIGN KEY (SNID) REFERENCES Airplane (SNID) ON DELETE CASCADE
);
