CREATE TABLE Airplane(
SNID INTEGER PRIMARY KEY NOT NULL,
capacity INTEGER,
max_speed REAL
)

CREATE TABLE PrivateJet(
owner_name CHAR(40),
FOREIGN KEY(SNID) REFERENCES(Airplane) ON DELETE CASCADE
)


CREATE TABLE CommercialPlane(
airline_name CHAR(40),
FOREIGN KEY(SNID) REFERENCES(Airplane) ON DELETE CASCADE
)